### ISSUE TITLE
Question about the code for finetuning

### ISSUE THREAD

**Issue by katie312** [yasamin-med/MEDDAP#2]
Hi, thank you for your work. I am confused that the paper suggests that the parameters needed for fine-tuning are smaller than those for global fine-tuning. However, when I looked at train_text_to_image_lora.py, the content seemed to be the same as the examples given in the diffusers library. Has the code not been updated yet?

**Comment by yasamin-med** [comment]
Hi,
Thanks for reaching out. We use the same code as diffusion model with lora
in hugging face. The networks is the same as before but they add lora
weights to the architecture and the rest of the network is freezed. So the
number of parameters which is updated is really smaller than the whole of
the network. Let me know if you have any other questions.

**Comment by katie312** [comment]
I understand now, thank you for clarifying.
